name: Update EC2 Host Secret After Terraform Apply

on:
  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed

jobs:
  update_secret:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: Get EC2 Public IP
        id: get_ip
        run: |
          cd terraform
          terraform init -backend=false
          terraform output -raw ec2_public_ip > ec2_host.txt
          echo "EC2_HOST=$(cat ec2_host.txt)" >> $GITHUB_ENV

      - name: Update GitHub Secret EC2_HOST
        uses: gliech/create-github-secret-action@v1
        with:
          name: EC2_HOST
          value: ${{ env.EC2_HOST }}
          token: ${{ secrets.GITHUB_TOKEN }}
