name: Update EC2 Host Secret and Trigger CI/CD

on:
  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed

jobs:
  update_ec2_secret:
    name: Update EC2 Host Secret
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: Get EC2 Public IP
        id: get_ip
        run: |
          cd terraform
          terraform init -backend=false
          echo "EC2_HOST=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV

      - name: Update GitHub Secret EC2_HOST
        uses: gliech/create-github-secret-action@v1
        with:
          name: EC2_HOST
          value: ${{ env.EC2_HOST }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trigger_cicd:
    name: Trigger CI/CD Pipeline
    needs: update_ec2_secret
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CI/CD Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: CI/CD Pipeline
          token: ${{ secrets.GITHUB_TOKEN }}
